### ISSUE TITLE
AsciiDoc support

### ISSUE THREAD

**Issue by RobWin** [devbliss/changelog-gradle-plugin#30]
Hello, 
could you please add support for AsciiDoc?

**Comment by RobWin** [comment]
Shameless plug: You could use my https://github.com/RobWin/markup-document-builder,
if you don't want to create an own solution.

**Comment by bodiam** [comment]
Also a shameless plug, but you could also integrate https://github.com/bodiam/markdown-to-asciidoc, which might also help a bit here?

**Comment by RobWin** [comment]
Nice. Could you show some code examples in your readme?

**Comment by bodiam** [comment]
Well, I could, but it would be this:

    assertEquals("= Title", Converter.convertMarkdownToAsciiDoc("# Title");

There is no configuration, no options, nothing. But I'll add it.

**Comment by retrostyle** [comment]
Hey guys,

sorry that we write so late, i will put this feature request in our next sprint so we will implement this... 

If someone is still working on this feature please make a pull request and than we can merge it... :)

thx

**Comment by RobWin** [comment]
It allows to include the output into existing AsciiDoc documentation
